In [156]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [157]:
df = sns.load_dataset('iris')

In [158]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [159]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [160]:
from sklearn.model_selection import train_test_split

In [161]:
X=df.drop(columns=['species'])
y=df['species']

In [162]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [163]:
from sklearn.neighbors import KNeighborsClassifier

In [164]:
knn_model=KNeighborsClassifier(n_neighbors=13)
knn_model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [165]:
y_pred=knn_model.predict(X_test)

In [166]:
knn_model.score(X_test,y_test)

1.0

In [167]:
from sklearn.svm import SVC

In [168]:
model_svm=SVC( gamma='auto' )

In [169]:
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [170]:
model_svm.score(X_test,y_test)

1.0

In [171]:
### use the gridCV for better results

In [172]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV

In [173]:
classifier =GridSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel' :['rbf','linear'],
},cv=5,return_train_score=False
                        )

In [174]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [175]:
classifier.cv_results_

{'mean_fit_time': array([0.00254641, 0.00254841, 0.00208473, 0.00232635, 0.00158749,
        0.00175433, 0.0019392 , 0.00198188]),
 'std_fit_time': array([0.00062237, 0.00091778, 0.00040949, 0.00069376, 0.00016597,
        0.00023927, 0.00029916, 0.00046654]),
 'mean_score_time': array([0.00160389, 0.00172892, 0.00156097, 0.00152965, 0.0011704 ,
        0.00132542, 0.00140791, 0.00151591]),
 'std_score_time': array([0.00030725, 0.00014287, 0.00037869, 0.00026551, 0.0001073 ,
        0.00033915, 0.00027553, 0.00019416]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [176]:
results = pd.DataFrame(classifier.cv_results_)

In [177]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002546,0.000622,0.001604,0.000307,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002548,0.000918,0.001729,0.000143,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002085,0.000409,0.001561,0.000379,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002326,0.000694,0.001530,0.000266,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.001587,0.000166,0.001170,0.000107,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.001754,0.000239,0.001325,0.000339,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.001939,0.000299,0.001408,0.000276,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.001982,0.000467,0.001516,0.000194,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [178]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [179]:
# knn model

In [180]:
param_grid = {
    'n_neighbors': [3, 5, 7, 9],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
}

In [181]:
classifier2=GridSearchCV((knn_model),param_grid,cv=5,return_train_score=False)
classifier2.fit(X, y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=13),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9],
                         'weights': ['uniform', 'distance']})

In [182]:
resutls2 =pd.DataFrame(classifier2.cv_results_)

In [183]:
resutls2[['param_n_neighbors','param_weights','param_metric','mean_test_score']].sort_values(by='mean_test_score',ascending=False)

    param_n_neighbors param_weights param_metric  mean_test_score
4                   7       uniform    euclidean         0.980000
5                   7      distance    euclidean         0.980000
2                   5       uniform    euclidean         0.973333
6                   9       uniform    euclidean         0.973333
7                   9      distance    euclidean         0.973333
12                  7       uniform    manhattan         0.973333
0                   3       uniform    euclidean         0.966667
1                   3      distance    euclidean         0.966667
3                   5      distance    euclidean         0.966667
14                  9       uniform    manhattan         0.966667
10                  5       uniform    manhattan         0.960000
11                  5      distance    manhattan         0.960000
13                  7      distance    manhattan         0.960000
15                  9      distance    manhattan         0.960000
8                   3       uniform    manhattan         0.960000
9                   3      distance    manhattan         0.960000

In [184]:
#random search cv

In [186]:
classifierReandom =RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel' :['rbf','linear'],
},n_iter=5,cv=5,return_train_score=False
                        )

In [187]:
classifierReandom.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=5,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [191]:
resultsRandom=pd.DataFrame(classifierReandom.cv_results_)

In [192]:
resultsRandom

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002270,0.000439,0.001556,0.000226,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002338,0.000791,0.001508,0.000339,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
2,0.001544,0.000049,0.001169,0.000120,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,4
3,0.001455,0.000013,0.001071,0.000039,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,4
4,0.001494,0.000149,0.001047,0.000035,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,2